blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/ck37X6UWBp 
    about: You can join our Discord for faster support aswell as additional help by the community.
